version: '3.7'
services:
  reverse-proxy:
    image: traefik # The official Traefik docker image
    command:
      - --api
      - --debug
      - --docker
      - --docker.swarmMode
      - --docker.watch
      - --docker.network=proxy
      - --defaultentrypoints=http
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 8080
        published: 8080
        mode: host
    networks:
      - proxy
    volumes:
      - traefik-tmp:/tmp
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
    deploy:
      replicas: 1
      mode: replicated
networks:
  proxy:
    name: proxy
    driver: overlay
volumes:
  traefik-tmp: