version: '3.7'

services:
  portainer:
    image: portainer/portainer
    volumes:
      - portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports: 
      - 9000:9000
volumes:
  portainer:
  traefik-tmp: