version: '3.7'

services:
  portainer:
    image: portainer/portainer:1.20.1
    volumes:
      - portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      replicas: 1
      mode: replicated
      labels:
        - traefik.docker.network=proxy
        - traefik.port=9000
        - traefik.backend=portainer
        - traefik.frontend.headers.frameDeny=true
        - traefik.frontend.rule=Host:portainer.customDomain.local
    networks:
      - proxy
      - portainer
  agent:
    image: portainer/agent:1.2.1
    networks:
      - portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    deploy:
      mode: global
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
volumes:
  portainer:
networks:
  portainer: 
    name: portainer
  proxy:
    external: true